### ISSUE TITLE
many warning in webstorm. hope fix it

### ISSUE THREAD

**Issue by hinego** [accelist/nextjs-starter#29]
![k1](https://os.skyqq.cc/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-11-18%20181705.png)
![k1](https://os.skyqq.cc/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-11-18%20181724.png)

**Comment by ryanelian** [comment]
Thank you for the bug report,

Unfortunately, I cannot reproduce your issue using the De Facto TypeScript and ESLint command line tools, nor the error show up in Visual Studio Code

```
PS D:\VS\accelist-nextjs-starter> npx tsc
PS D:\VS\accelist-nextjs-starter> npx next lint
✔ No ESLint warnings or errors
```
